const ACTION_TYPE = {
  SEND_MSG_ACTION: "SEND_MSG_ACTION",
  SEND_MSG_REQUEST: "SEND_MSG_REQUEST",
  SEND_MSG_SUCCESS: "SEND_MSG_SUCCESS",
  SEND_MSG_ERROR: "SEND_MSG_ERROR",
  GET_MSG_REQUEST: "GET_MSG_REQUEST",
  GET_MSG_SUCCESS: "GET_MSG_SUCCESS",
  GET_MSG_ERROR: "GET_MSG_ERROR",
};
export default ACTION_TYPE;
